#pragma once

// Component reflection metadata: shared by the serialization code in World.h and the
// editor UI. The TYPES and the GENERATOR live here (hand-written, stable). The DATA
// (the InitKnownComponents() body) lives in the autogenerated ComponentMetaData.h, which
// is produced by ParseCpp() reading World.h. Keep these two files distinct.
//
// This header is included from World.h (right before UIHelpers.h) so it only needs
// Components::Mask and String to be defined.

#include <fstream>
#include <vector>
#include <format>
#include <string>

enum class PropertyTypes : int
{
    _none,
    _int,
    _uint,
    _float,
    _float2,
    _float3,
    _float4,
    _quaternion,
    _float4x4,
    _assetID,
    _Handle,
    _bool,
    _raw    // any type the generator doesn't otherwise recognize (e.g. char, enums)
};
bool KnownType(String typeName)
{
    if (typeName == "int")
        return true;
    else if (typeName == "uint")
        return true;
    else if (typeName == "float")
        return true;
    else if (typeName == "float2")
        return true;
    else if (typeName == "float3")
        return true;
    else if (typeName == "float4")
        return true;
    else if (typeName == "quaternion")
        return true;
    else if (typeName == "float4x4")
        return true;
    else if (typeName == "assetID")
        return true;
    else if (typeName == "Handle")
        return true;
    else if (typeName == "bool")
        return true;
    return false;
}
struct MemberInfoParse
{
    String name;
    String dataType;
    String dataTemplateType;
    String dataCount;
};
struct ComponentInfoParse
{
    String name;
    std::vector<MemberInfoParse> members;
    String propertyDrawPtr;
};
struct MemberInfo
{
    String name;
    PropertyTypes dataType;
    Components::Mask dataTemplateType;
    int dataCount;
    int offset;
};
struct ComponentInfo
{
    String name;       // Component name
    Components::Mask mask;
    void (*PropertyDraw)(char*);
    std::vector<MemberInfo> members;
};
std::vector<ComponentInfo> knownComponents;

String FormatComponentsArray(std::vector<String>& componentsInfo)
{
    String out = "ComponentInfo knownComponents[] = \n{\n";

    for (uint i = 0; i < componentsInfo.size(); i++)
    {
        auto& name = componentsInfo[i];
        out += std::format("\t{}MetaData,\n", name.c_str());
    }

    out += "};\n";

    return out;
}
String FormatMetaData(ComponentInfoParse cmpInfo, uint& cmpIndex)
{
    String out = std::format("knownComponents.push_back(\n \t{{ \"{0}\", Components::{0}::mask, {1}, \n \t\t{{\n", cmpInfo.name.c_str(), cmpInfo.propertyDrawPtr.c_str());

    for (uint i = 0; i < cmpInfo.members.size(); i++)
    {
        auto& m = cmpInfo.members[i];
        out += std::format("\t\t\t{{ \"{0}\", PropertyTypes::_{1}, {2}, {3}, offsetof(Components::{4}, {0}) }},\n", m.name.c_str(), m.dataType.c_str(), m.dataTemplateType.c_str(), m.dataCount.c_str(), cmpInfo.name.c_str());
    }

    out += "\t\t}\n \t}";
    out += "); \n";

    cmpIndex++;
    return out;
}
// Returns true if this struct-body line looks like a plain field declaration
// (Type name;) rather than a method, enum, macro, access specifier, etc.
static bool LooksLikeFieldDecl(String& firstToken, String& line)
{
    if (firstToken.empty())
        return false;
    if (firstToken[0] == '#')                 // #define / #pragma
        return false;
    if (firstToken.find("//") != -1)          // comment
        return false;
    if (firstToken == "enum" || firstToken == "struct" || firstToken == "union" ||
        firstToken == "class" || firstToken == "static" || firstToken == "template" ||
        firstToken == "public:" || firstToken == "private:" || firstToken == "protected:" ||
        firstToken == "typedef" || firstToken == "using" || firstToken == "friend" ||
        firstToken == "return")
        return false;
    if (line.find("(") != -1)                 // method / constructor
        return false;
    if (line.find(";") == -1)                 // not a declaration
        return false;
    return true;
}
void ParseCpp(String path)
{
    std::ifstream fin(path);
    std::ofstream fout("G:\\Work\\Dev\\SeeD\\SeeD\\src\\ComponentMetaData.h");
    if (fin.is_open() && fout.is_open())
    {
        fout << "#pragma once" << std::endl;

        fout << "void InitKnownComponents() { \n" << std::endl;
        fout << "static bool initialized = false;\n" << std::endl;
        fout << "if(initialized) return;\n" << std::endl;
        fout << "initialized = true;\n" << std::endl;

        std::vector<ComponentInfoParse> cmpInfos;
        String line;
        uint cmpIndex = 0;
        while (getline(fin, line))
        {
            if (line.find(": ComponentBase<") != -1)
            {
                auto tokens = line.Split(" ");
                cmpInfos.resize(cmpInfos.size() + 1);
                ComponentInfoParse& cmpInfo = cmpInfos[cmpInfos.size() - 1];
                cmpInfo.propertyDrawPtr = "nullptr";
                cmpInfo.name = tokens[1];
                while (line.find("};") == -1)
                {
                    getline(fin, line);
                    tokens = line.Split(" ");
                    if (tokens.size() >= 2)
                    {
                        String typeToken = tokens[0];
                        if (!LooksLikeFieldDecl(typeToken, line))
                            continue;

                        String templateTypeToken = "NULL";
                        int chevron = (int)typeToken.find("<");
                        if (chevron != -1)
                        {
                            templateTypeToken = typeToken.substr(chevron + 1, typeToken.find(">") - chevron - 1);
                            templateTypeToken = std::format("Components::{0}::mask", templateTypeToken.c_str());
                            typeToken = typeToken.substr(0, chevron);
                        }

                        MemberInfoParse info;
                        // Unknown types are kept as _raw so the field list always covers
                        // the whole struct (and no handle is ever silently dropped).
                        info.dataType = KnownType(typeToken) ? typeToken : String("raw");
                        info.dataTemplateType = templateTypeToken;

                        String nameToken = tokens[1];
                        int semi = (int)nameToken.find(";");
                        if (semi != -1)
                            nameToken = nameToken.substr(0, semi);
                        int bracketIndex = (int)nameToken.find("[");
                        if (bracketIndex != -1)
                        {
                            int bracketIndexOut = (int)nameToken.find("]");
                            info.dataCount = nameToken.substr(bracketIndex + 1, bracketIndexOut - bracketIndex - 1);
                            info.name = nameToken.substr(0, bracketIndex);
                        }
                        else
                        {
                            info.dataCount = "1";
                            info.name = nameToken;
                        }
                        cmpInfo.members.push_back(info);
                    }
                }
            }
            else if (line.find("PropertyDraw(") != -1)
            {
                int start = (int)line.find("void ") + 5;
                int end = (int)line.find("PropertyDraw(");
                String drawTarget = line.substr(start, end - start);

                for (uint i = 0; i < (uint)cmpInfos.size(); i++)
                {
                    if (cmpInfos[i].name == drawTarget)
                    {
                        int start = (int)line.find("void ") + 5;
                        int end = (int)line.find("(");
                        String funcName = line.substr(start, end - start);
                        cmpInfos[i].propertyDrawPtr = "Components::" + funcName;
                    }
                }
            }
        }

        for (uint i = 0; i < (uint)cmpInfos.size(); i++)
        {
            fout << FormatMetaData(cmpInfos[i], cmpIndex);
        }

        fout << "}\n" << std::endl;

        fin.close();
        fout.close();
    }
}

// Cheap sanity tripwire: confirm each component's last (highest-offset) field actually
// fits inside the struct. Combined with the generator capturing every member, this is
// enough to be confident the table is a good base. Call after InitKnownComponents().
void VerifyKnownComponents()
{
    for (uint i = 0; i < knownComponents.size(); i++)
    {
        auto& cmp = knownComponents[i];
        uint bucket = Components::MaskToBucket(cmp.mask);
        uint stride = Components::strides[bucket];
        for (uint m = 0; m < cmp.members.size(); m++)
        {
            if ((uint)cmp.members[m].offset >= stride)
            {
                IOs::Log("Metadata error: {}.{} offset {} >= stride {}",
                    cmp.name.c_str(), cmp.members[m].name.c_str(), cmp.members[m].offset, stride);
                seedAssert(false);
            }
            // Members must be in strictly ascending offset order: the serializer derives each
            // field's byte size from the next field's offset (no sort) and SaveEntities writes
            // fields in this order. Out-of-order here means a STALE ComponentMetaData.h --
            // regenerate it via the "Generate components Metadata" menu after editing a
            // component's fields (it always emits declaration order == ascending offset order).
            if (m > 0 && cmp.members[m].offset <= cmp.members[m - 1].offset)
            {
                IOs::Log("Metadata error: {} members out of offset order ('{}' offset {} <= '{}' offset {}) -- regenerate ComponentMetaData.h",
                    cmp.name.c_str(), cmp.members[m].name.c_str(), cmp.members[m].offset,
                    cmp.members[m - 1].name.c_str(), cmp.members[m - 1].offset);
                seedAssert(false);
            }
        }
    }
}
